spring.application.name=identity-lab
spring.datasource.url=jdbc:postgresql://localhost:5432/identity_lab
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=identity-lab-secret-key-for-learning-project-2026
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
jwt.jarm-expiration=300000

identity.issuer=http://localhost:8080

server.ssl.enabled=true
server.ssl.key-store=certs/server.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=identity-lab-server
server.ssl.trust-store=certs/server-truststore.p12
server.ssl.trust-store-password=123456
server.ssl.trust-store-type=PKCS12
server.ssl.client-auth=need